#
###################################
# Site wide configuration
####################################
#
title: 2da
email: daeun9294@gmail.com
description: 이다 블로그
url: https://daeun1012.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Android", "Swift", "Kotlin", "안드로이드"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Korea/Asia
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ida
  avatar: main_profile.jpg
  job: "Mobile Developer"
  bio: "Nothing great in the world has been accomplished without <strong>passion.</strong>"
  email: daeun9294@gmail.com
  disqus-shortname: #renyuanzblog
  twitter: #renyuan814 #username
  facebook: 100001772488008
  google:
    plus: #username
    analytics: UA-110187793-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: daeun1012 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #renyuan-zou-69b7038a #username
  xing: #username
  instagram: 2da_a
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: daeunlee
